### ISSUE TITLE
Command needs 'import bpy' to be call for every time.

### ISSUE THREAD

**Issue by rootaman** [p4vv37/blender_command_port#1]
Test on Blender 2.8 beta, I have to included "import bpy;" for every command session sending to the port.

**Comment by p4vv37** [comment]
Hi
I've added an option to "share environment" with executed scripts. It shares globals with them and copies locals of them to globals, introduced in [commit](https://github.com/p4vv37/blender_command_port/commit/38e387633cd1ebe30575e37d9435fb3c92ef35b1) 
Also, I've added a test for that functionality.

**Comment by p4vv37** [comment]
As described ealier, this should work now as expected
