### ISSUE TITLE
Invalid name inside zip release folder prevents installation

### ISSUE THREAD

**Issue by Radivarig** [p4vv37/blender_command_port#15]
Release file throws:
```
ModuleNotFoundError: No module named 'blender_command_port-1'
```
Which is the part of the folder name inside the zip release file before the first dot `blender_command_port-1.1.2`.

Also the versions don't match, release is marked as 1.2.0, but the source is 1.1.2.

**Comment by p4vv37** [comment]
3 years later, 2.0.0 had the same error :) Thanks, fixed it
