### ISSUE TITLE
Some necessary adjustments I made to turn on the plugin in Blender 2.93

### ISSUE THREAD

**Issue by KevynTD** [p4vv37/blender_command_port#17]
The plugin is amazing, but it needed these adjustments to work here on my computer:

After installing the plugin in Blender 2.93, in this file:
`C:\Users\YOUR_USER\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender_command_port-master\command_port.py`

Comment the line 20 and 21 (because I don't use pycharm):
> From
> ```
> import pydevd_pycharm
> pydevd_pycharm.settrace('localhost', port=6666, stdoutToServer=True, stderrToServer=True)
> ```
> to
> ```
> # import pydevd_pycharm
> # pydevd_pycharm.settrace('localhost', port=6666, stdoutToServer=True, stderrToServer=True)
> ```

And change in line 82 `t.isAlive()` to `t.is_alive()` (according [this thread doc from Python3](https://docs.python.org/3/library/threading.html#threading.Thread.is_alive)):
> from
> ```
> while any([t.name == "MainThread" and t.isAlive() for t in threads]):
> ```
> to
> ```
> while any([t.name == "MainThread" and t.is_alive() for t in threads]):
> ```

So I managed to run without any errors.

**Comment by lixiaotaowx** [comment]
3.1 Cannot be opened？why？
![1650988306(1)](https://user-images.githubusercontent.com/103853019/165341581-93b80fed-6bc1-42d1-bb71-d88d1f73e0af.png)

**Comment by KevynTD** [comment]
> 3.1 Cannot be opened？why？ ![1650988306(1)](https://user-images.githubusercontent.com/103853019/165341581-93b80fed-6bc1-42d1-bb71-d88d1f73e0af.png)

@lixiaotaowx I'm not the author of the plugin, but I would recommend opening a new issue with more details like the error message in the console.
For that, close everything, open blender, go to "Window ‣ Toggle System Console" and then click "open port" , it will probably give errors in the console, these errors are important for the author to be able to adjust the program for it to work

**Comment by p4vv37** [comment]
Thank you for contribution, the changes are merged, so I'm closing the thread.
