### ISSUE TITLE
Blender 3.2 - One small change needed: is_alive

### ISSUE THREAD

**Issue by hced** [p4vv37/blender_command_port#18]
Ran this tool in Blender 3.2 and got an error on line 85 in `command_port.py` complaining about the `isAlive` function call. Changed it to `is_alive` and the addon seems to work like a charm! (Also worth mentioning: I did not download the file from the releases page since that version is out of date: working directory is 1.2.1 and the 'latest' release is an older version.)

**Comment by lixiaotaowx** [comment]
I have been looking forward to the update, but it is clear that after many years, he seems to have given up

**Comment by lixiaotaowx** [comment]
If you have a good idea, remember to share it with me. Thank you very much

**Comment by p4vv37** [comment]
Thank you for the change, sorry for checking it so late.
Right, years have passed and I need to update my notification settings, apparently :sweat_smile:
