### ISSUE TITLE
Release 2.0.0 won't install after master uninstall

### ISSUE THREAD

**Issue by SwaggerNiels** [p4vv37/blender_command_port#22]
I have Blender 3.6 on a Windows machine.

I installed the master branch zip as an addon but found some irregular behaviour.
But now the problem is:

The release seems uninstallable after I installed and uninstalled the master branch:
![afbeelding](https://github.com/p4vv37/blender_command_port/assets/58084010/f542e58b-0902-4bf9-948b-86ded225ddb1)
I think there is some naming issue here.

**Comment by p4vv37** [comment]
Thanks, this should be fixed in release [2.0.1](https://github.com/p4vv37/blender_command_port/releases/tag/2.0.1)

**Comment by p4vv37** [comment]
Thanks, this should be fixed in release [2.0.1](https://github.com/p4vv37/blender_command_port/releases/tag/2.0.1)
