### ISSUE TITLE
Cannot disable/remove properly

### ISSUE THREAD

**Issue by guestieng** [p4vv37/blender_command_port#5]
Hello,
the add-on cannot be disabled/removed properly (Blender version 2.81a):

- Issue "Disable":
1) Installed add-on from zip-file
2) Enabled add-on
3) Disabled add-on
-> error "rna_uiItemR: property not found: Scene.*"
-> error "rna_uiItemO: operator missing srna 'wm.open_command_port'"

- Issue "Remove":
1) Installed add-on from zip-file
2) Enabled add-on
3) Click Remove Button
-> Menu label "Blender Command Port" remains
-> installing and enabling again leads to error "ValueError: register_class(...): already registered as a subclass 'CommandPortOperator'"

**Comment by p4vv37** [comment]
Hi
thanks, I've fixed this in commit 7f13a59
