### ISSUE TITLE
Problem with execute_file_in_blender.py

### ISSUE THREAD

**Issue by guestieng** [p4vv37/blender_command_port#6]
Hello,
in the the basic usage description two ways are described how one can send python code to blender.
The first one works without errors.
The second way via the execute_file_in_blender.py, however, is not working (Blender 2.81a).
In particular, connection errors appear.
To this end I used the command 
$ python \<directory\>/execute_file_in_blender.py "\<directory\>/test.py" 5000
with test.py containing simple code like `print("test")`.
However, the same problems happen when using PyCharm as suggested.

**Comment by JeffHanna** [comment]
I submitted pull requests to fix this addon for Blender 2.8x. You can download a version that works from my Github for of the project
[Release 1.1.2](https://github.com/JeffHanna/blender_command_port/releases/tag/1.1.2)
