### ISSUE TITLE
Sending code continuously

### ISSUE THREAD

**Issue by guestieng** [p4vv37/blender_command_port#7]
Hello,
the add-on works fine via the first method described (i.e. not via execute_file_in_blender.py (see #6)).
However, so far, it only seems to be possible to process the sent command on the blender side when clicking the "Close Port" button. 
Is there already a way to process a sequence of sent commands with python code as soon as the commands are sent by the corresponding external python script, 
i.e. without closing/opening the port  each time?

**Comment by p4vv37** [comment]
Hi
Right, It should work instantly, just after sending the command, I've just tried to repro this:
![ex](https://user-images.githubusercontent.com/3722204/77617690-0d946400-6f35-11ea-93d7-cfd438f43bb6.gif)
And it worked fine

**Comment by p4vv37** [comment]
I really cannot reproduce it
